# Generated by Django 4.1.7 on 2023-11-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20231103_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='URL',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='source_url',
            field=models.CharField(blank=True, max_length=3000, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='LongUrl',
        ),
    ]
